/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 23
#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_SPACE(); /* 23 */
YY_RULE(int) yy_XREFTAB(); /* 22 */
YY_RULE(int) yy_EOL(); /* 21 */
YY_RULE(int) yy_STREAM(); /* 20 */
YY_RULE(int) yy_ARRAY(); /* 19 */
YY_RULE(int) yy_NUM(); /* 18 */
YY_RULE(int) yy_REF(); /* 17 */
YY_RULE(int) yy_ALPHANUM(); /* 16 */
YY_RULE(int) yy_ALPHA(); /* 15 */
YY_RULE(int) yy_DE(); /* 14 */
YY_RULE(int) yy_VALUE(); /* 13 */
YY_RULE(int) yy_KEY(); /* 12 */
YY_RULE(int) yy_DB(); /* 11 */
YY_RULE(int) yy_DICT(); /* 10 */
YY_RULE(int) yy_GOBBLE(); /* 9 */
YY_RULE(int) yy_STARTXREF(); /* 8 */
YY_RULE(int) yy_TRAILER(); /* 7 */
YY_RULE(int) yy_XREF(); /* 6 */
YY_RULE(int) yy_DELIM(); /* 5 */
YY_RULE(int) yy_OBJ(); /* 4 */
YY_RULE(int) yy_COMMENT(); /* 3 */
YY_RULE(int) yy_MAGIC(); /* 2 */
YY_RULE(int) yy_start(); /* 1 */

YY_ACTION(void) yy_1_MAGIC(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_MAGIC\n"));
  printf("start PDF...\n");;
}
YY_ACTION(void) yy_1_TRAILER(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_TRAILER\n"));
  printf(" trailer...\n");;
}
YY_ACTION(void) yy_1_XREFTAB(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_XREFTAB\n"));
  printf("xref_nnnn...\n");;
}
YY_ACTION(void) yy_1_XREF(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_XREF\n"));
  printf("xref...\n");;
}
YY_ACTION(void) yy_1_REF(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_REF\n"));
   printf("ref..\n"); ;
}
YY_ACTION(void) yy_1_STREAM(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_STREAM\n"));
  printf("stream...\n");;
}
YY_ACTION(void) yy_2_OBJ(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_OBJ\n"));
   printf("objend..\n"); ;
}
YY_ACTION(void) yy_1_OBJ(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_OBJ\n"));
   printf("objbegin..\n"); ;
}
YY_ACTION(void) yy_1_ARRAY(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_ARRAY\n"));
   printf("array..\n"); ;
}
YY_ACTION(void) yy_1_VALUE(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_VALUE\n"));
  printf("value\n");;
}
YY_ACTION(void) yy_1_KEY(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_KEY\n"));
  printf("key+");;
}
YY_ACTION(void) yy_1_DE(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_DE\n"));
  fprintf(stdout, "dictend\n");;
}
YY_ACTION(void) yy_1_DB(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_DB\n"));
  fprintf(stdout, "dictbegin\n");;
}

YY_RULE(int) yy_SPACE()
{
  yyprintf((stderr, "%s\n", "SPACE"));
  l2:;	
  {  int yypos3= yypos, yythunkpos3= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  goto l2;
  l3:;	  yypos= yypos3; yythunkpos= yythunkpos3;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "SPACE", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_XREFTAB()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "XREFTAB"));  if (!yy_NUM()) goto l4;  if (!yy_NUM()) goto l4;
  {  int yypos5= yypos, yythunkpos5= yythunkpos;  if (!yymatchChar('n')) goto l6;  goto l5;
  l6:;	  yypos= yypos5; yythunkpos= yythunkpos5;  if (!yymatchChar('f')) goto l4;
  }
  l5:;	  if (!yy_EOL()) goto l4;  yyDo(yy_1_XREFTAB, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "XREFTAB", yybuf+yypos));
  return 1;
  l4:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "XREFTAB", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_EOL()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yymatchChar('\n')) goto l9;  goto l8;
  l9:;	  yypos= yypos8; yythunkpos= yythunkpos8;  if (!yymatchString("\r\n")) goto l10;  goto l8;
  l10:;	  yypos= yypos8; yythunkpos= yythunkpos8;  if (!yymatchChar('\r')) goto l7;
  }
  l8:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yybuf+yypos));
  return 1;
  l7:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_STREAM()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STREAM"));  if (!yymatchString("stream")) goto l11;  if (!yy_EOL()) goto l11;
  l12:;	
  {  int yypos13= yypos, yythunkpos13= yythunkpos;
  {  int yypos14= yypos, yythunkpos14= yythunkpos;  if (!yymatchString("endstream")) goto l14;  goto l13;
  l14:;	  yypos= yypos14; yythunkpos= yythunkpos14;
  }  if (!yymatchDot()) goto l13;  goto l12;
  l13:;	  yypos= yypos13; yythunkpos= yythunkpos13;
  }  if (!yymatchString("endstream")) goto l11;  if (!yy_DELIM()) goto l11;  yyDo(yy_1_STREAM, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "STREAM", yybuf+yypos));
  return 1;
  l11:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STREAM", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ARRAY()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ARRAY"));  if (!yymatchChar('[')) goto l15;  if (!yy_DELIM()) goto l15;
  l16:;	
  {  int yypos17= yypos, yythunkpos17= yythunkpos;  if (!yy_VALUE()) goto l17;  goto l16;
  l17:;	  yypos= yypos17; yythunkpos= yythunkpos17;
  }  if (!yymatchChar(']')) goto l15;  if (!yy_DELIM()) goto l15;  yyDo(yy_1_ARRAY, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ARRAY", yybuf+yypos));
  return 1;
  l15:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ARRAY", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_NUM()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NUM"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l18;
  l19:;	
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l20;  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  if (!yy_DELIM()) goto l18;
  yyprintf((stderr, "  ok   %s @ %s\n", "NUM", yybuf+yypos));
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUM", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_REF()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "REF"));  if (!yy_DELIM()) goto l21;  if (!yy_NUM()) goto l21;  if (!yy_NUM()) goto l21;  if (!yymatchChar('R')) goto l21;  if (!yy_DELIM()) goto l21;  if (!yy_DELIM()) goto l21;  yyDo(yy_1_REF, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "REF", yybuf+yypos));
  return 1;
  l21:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "REF", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ALPHANUM()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ALPHANUM"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l22;
  yyprintf((stderr, "  ok   %s @ %s\n", "ALPHANUM", yybuf+yypos));
  return 1;
  l22:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ALPHANUM", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ALPHA()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ALPHA"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "ALPHA", yybuf+yypos));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ALPHA", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DE()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DE"));  if (!yymatchString(">>")) goto l24;  if (!yy_DELIM()) goto l24;  yyDo(yy_1_DE, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "DE", yybuf+yypos));
  return 1;
  l24:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DE", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_VALUE()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "VALUE"));
  {  int yypos26= yypos, yythunkpos26= yythunkpos;  if (!yy_REF()) goto l27;  goto l26;
  l27:;	  yypos= yypos26; yythunkpos= yythunkpos26;  if (!yy_NUM()) goto l28;  goto l26;
  l28:;	  yypos= yypos26; yythunkpos= yythunkpos26;  if (!yy_KEY()) goto l29;  goto l26;
  l29:;	  yypos= yypos26; yythunkpos= yythunkpos26;  if (!yy_DICT()) goto l30;  goto l26;
  l30:;	  yypos= yypos26; yythunkpos= yythunkpos26;  if (!yy_ARRAY()) goto l25;
  }
  l26:;	  if (!yy_DELIM()) goto l25;  yyDo(yy_1_VALUE, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "VALUE", yybuf+yypos));
  return 1;
  l25:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VALUE", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_KEY()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "KEY"));  if (!yymatchChar('/')) goto l31;  if (!yy_ALPHA()) goto l31;
  l32:;	
  {  int yypos33= yypos, yythunkpos33= yythunkpos;  if (!yy_ALPHANUM()) goto l33;  goto l32;
  l33:;	  yypos= yypos33; yythunkpos= yythunkpos33;
  }  if (!yy_DELIM()) goto l31;  yyDo(yy_1_KEY, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "KEY", yybuf+yypos));
  return 1;
  l31:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "KEY", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DB()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DB"));  if (!yymatchString("<<")) goto l34;  if (!yy_DELIM()) goto l34;  yyDo(yy_1_DB, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "DB", yybuf+yypos));
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DB", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DICT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DICT"));  if (!yy_DELIM()) goto l35;  if (!yy_DB()) goto l35;
  l36:;	
  {  int yypos37= yypos, yythunkpos37= yythunkpos;  if (!yy_KEY()) goto l37;  if (!yy_VALUE()) goto l37;  goto l36;
  l37:;	  yypos= yypos37; yythunkpos= yythunkpos37;
  }  if (!yy_DE()) goto l35;  if (!yy_DELIM()) goto l35;
  yyprintf((stderr, "  ok   %s @ %s\n", "DICT", yybuf+yypos));
  return 1;
  l35:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DICT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_GOBBLE()
{
  yyprintf((stderr, "%s\n", "GOBBLE"));
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yymatchDot()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "GOBBLE", yybuf+yypos));
  return 1;
}
YY_RULE(int) yy_STARTXREF()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STARTXREF"));  if (!yymatchString("startxref")) goto l41;  if (!yy_DELIM()) goto l41;  if (!yy_NUM()) goto l41;  if (!yy_DELIM()) goto l41;
  yyprintf((stderr, "  ok   %s @ %s\n", "STARTXREF", yybuf+yypos));
  return 1;
  l41:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STARTXREF", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_TRAILER()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "TRAILER"));  if (!yymatchString("trailer")) goto l42;  if (!yy_DELIM()) goto l42;  if (!yy_DICT()) goto l42;  if (!yy_DELIM()) goto l42;  yyDo(yy_1_TRAILER, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "TRAILER", yybuf+yypos));
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TRAILER", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_XREF()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "XREF"));  if (!yymatchString("xref")) goto l43;  if (!yy_EOL()) goto l43;  if (!yy_NUM()) goto l43;  if (!yy_NUM()) goto l43;
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_XREFTAB()) goto l45;  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }  yyDo(yy_1_XREF, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "XREF", yybuf+yypos));
  return 1;
  l43:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "XREF", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_DELIM()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DELIM"));  if (!yy_SPACE()) goto l46;
  l47:;	
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy_EOL()) goto l48;  goto l47;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "DELIM", yybuf+yypos));
  return 1;
  l46:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DELIM", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_OBJ()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OBJ"));  if (!yy_DELIM()) goto l49;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l49;
  l50:;	
  {  int yypos51= yypos, yythunkpos51= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l51;  goto l50;
  l51:;	  yypos= yypos51; yythunkpos= yythunkpos51;
  }  if (!yymatchChar(' ')) goto l49;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l49;
  l52:;	
  {  int yypos53= yypos, yythunkpos53= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l53;  goto l52;
  l53:;	  yypos= yypos53; yythunkpos= yythunkpos53;
  }  if (!yymatchChar(' ')) goto l49;  if (!yymatchString("obj")) goto l49;  if (!yy_DELIM()) goto l49;  yyDo(yy_1_OBJ, yybegin, yyend);
  l54:;	
  {  int yypos55= yypos, yythunkpos55= yythunkpos;
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yy_REF()) goto l57;  goto l56;
  l57:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yy_DICT()) goto l58;  goto l56;
  l58:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yy_NUM()) goto l59;  goto l56;
  l59:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yy_ARRAY()) goto l55;
  }
  l56:;	  goto l54;
  l55:;	  yypos= yypos55; yythunkpos= yythunkpos55;
  }
  l60:;	
  {  int yypos61= yypos, yythunkpos61= yythunkpos;  if (!yy_STREAM()) goto l61;  goto l60;
  l61:;	  yypos= yypos61; yythunkpos= yythunkpos61;
  }  if (!yymatchString("endobj")) goto l49;  if (!yy_DELIM()) goto l49;  yyDo(yy_2_OBJ, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "OBJ", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OBJ", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_COMMENT()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COMMENT"));  if (!yymatchChar('%')) goto l62;
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yymatchChar('%')) goto l64;  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }
  l65:;	
  {  int yypos66= yypos, yythunkpos66= yythunkpos;
  {  int yypos67= yypos, yythunkpos67= yythunkpos;  if (!yy_EOL()) goto l67;  goto l66;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }  if (!yymatchDot()) goto l66;  goto l65;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }  if (!yy_EOL()) goto l62;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMENT", yybuf+yypos));
  return 1;
  l62:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMENT", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_MAGIC()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MAGIC"));  if (!yymatchChar('%')) goto l68;
  l69:;	
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yymatchChar('%')) goto l70;  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\001\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l68;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\020\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l68;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\100\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l68;
  l71:;	
  {  int yypos72= yypos, yythunkpos72= yythunkpos;
  {  int yypos73= yypos, yythunkpos73= yythunkpos;  if (!yy_EOL()) goto l73;  goto l72;
  l73:;	  yypos= yypos73; yythunkpos= yythunkpos73;
  }  if (!yymatchDot()) goto l72;  goto l71;
  l72:;	  yypos= yypos72; yythunkpos= yythunkpos72;
  }  if (!yy_EOL()) goto l68;  yyDo(yy_1_MAGIC, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "MAGIC", yybuf+yypos));
  return 1;
  l68:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MAGIC", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_start()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "start"));  if (!yy_MAGIC()) goto l74;
  l75:;	
  {  int yypos76= yypos, yythunkpos76= yythunkpos;  if (!yy_COMMENT()) goto l76;  goto l75;
  l76:;	  yypos= yypos76; yythunkpos= yythunkpos76;
  }  if (!yy_OBJ()) goto l74;
  l77:;	
  {  int yypos78= yypos, yythunkpos78= yythunkpos;  if (!yy_OBJ()) goto l78;  goto l77;
  l78:;	  yypos= yypos78; yythunkpos= yythunkpos78;
  }  if (!yy_DELIM()) goto l74;  if (!yy_XREF()) goto l74;  if (!yy_DELIM()) goto l74;  if (!yy_TRAILER()) goto l74;  if (!yy_STARTXREF()) goto l74;  if (!yy_GOBBLE()) goto l74;
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yybuf+yypos));
  return 1;
  l74:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_start);
}

#endif
